# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: ~/overleaf
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: make

  badge:
    machine: true
    steps:
      - run:
          name: "Call microbadger's webhook"
          command: curl -X POST https://hooks.microbadger.com/images/unibaktr/overleaf/gizyokiZzOAJ1aoILvmanv-Tt7Y=

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/

workflows:
  build-and-badge:
    jobs:
      - build:
          <<: *tag_filter
      - badge:
          requires:
            - build
          <<: *tag_filter
